name: Run Tests

on:
  pull_request:
  push:
    branches: master

jobs:
  laravel-10:
    name: Latest version Laravel ${{ matrix.laravel-versions }} PHP ${{ matrix.php-versions }} ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '8.1' ]
        laravel-versions: [ '^10.0' ]

    steps:
      - uses: matriphe/laravel-pkg-test-action@v2
        with:
          operating_system: ${{ matrix.operating-system }}
          php_version: ${{ matrix.php-versions }}
          laravel_version: ${{ matrix.laravel-versions }}
          phpunit_args: --group unit
          laravel_install_args: --prefer-dist --no-progress --no-suggest --optimize-autoloader --no-plugins
          package_install_args: --prefer-dist --no-progress --no-suggest --optimize-autoloader --no-plugins

      - name: Execute tests
        run: composer test


  laravel-9-older:
    name: Laravel ${{ matrix.laravel-versions }} PHP ${{ matrix.php-versions }} ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '8.0' ]
        laravel-versions: [ '^7.0', '^8.0', '^9.0' ]

    steps:
      - uses: matriphe/laravel-pkg-test-action@v2
        with:
          operating_system: ${{ matrix.operating-system }}
          php_version: ${{ matrix.php-versions }}
          laravel_version: ${{ matrix.laravel-versions }}
          phpunit_args: --group unit
          laravel_install_args: --prefer-dist --no-progress --no-suggest --optimize-autoloader --no-plugins --ignore-platform-req=php+
          package_install_args: --prefer-dist --no-progress --no-suggest --optimize-autoloader --no-plugins --ignore-platform-req=php+
          branch: 0.3.0

      - name: Execute tests
        run: composer test
